url: https://jaike.netlify.com
baseurl: 

# Site settings
title: Jaike Belfor
email: your-email@domain.com
description: Dit is de website van Jaike Belfor. In ben ik afgestudeerd aan de acteursopleiding in Utrecht (HKU). Ik ben een actrice en theatermaker. Ik heb gespeeld in verschillende theatervoorstelling. Op televisie was ik te zien in de televisieserie Celblok H als Boomer. En natuurlijk ook als finalist van de slimste mens 2018.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100015482732211
  - title: instagram
    url: https://www.instagram.com/jaikebelfor/
  - title: imdb
    url: https://www.imdb.com/name/nm2321536/    
  - title: github
    url: https://github.com/rickx1/jaike.nl

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty